/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_encomienda.GESTION_PAQUETES.FRONTEND;
import proyecto_encomienda.GESTION_PAQUETES.FRONTEND.ClasesExtras.MovePanelWithAnimation;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */

public class PaqueteMenu extends javax.swing.JFrame {
    
    MovePanelWithAnimation mover;
    /**
     * Creates new form Paquete
     */
    public PaqueteMenu() {
        initComponents();
        this.setLocationRelativeTo(null); //Se centre la pantalla
        this.mover = new MovePanelWithAnimation();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jPControl = new javax.swing.JPanel();
        jLSelectH = new javax.swing.JLabel();
        jMinimizarMenu = new javax.swing.JLabel();
        jLHome = new javax.swing.JLabel();
        jLLineaH = new javax.swing.JLabel();
        jLSelectA = new javax.swing.JLabel();
        jLAdministracion = new javax.swing.JLabel();
        jLLineaA = new javax.swing.JLabel();
        jLSelectP = new javax.swing.JLabel();
        jLPaqueteria = new javax.swing.JLabel();
        jLLineaP = new javax.swing.JLabel();
        jLSelectF = new javax.swing.JLabel();
        jLFactura = new javax.swing.JLabel();
        jLLineaF = new javax.swing.JLabel();
        jLSelectI = new javax.swing.JLabel();
        jLIncidentes = new javax.swing.JLabel();
        jLLineaI = new javax.swing.JLabel();
        jLSelectT = new javax.swing.JLabel();
        jLTransporte = new javax.swing.JLabel();
        jLLineaT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAdm = new javax.swing.JLabel();
        btnPac = new javax.swing.JLabel();
        btnFac = new javax.swing.JLabel();
        btnInc = new javax.swing.JLabel();
        btnTran = new javax.swing.JLabel();
        btnHom = new javax.swing.JLabel();
        jMenu = new javax.swing.JLabel();
        jPAdministracion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPIncidentes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPFactura = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPTransporte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPPaqueteria = new javax.swing.JPanel();
        jLSelectInventario = new javax.swing.JLabel();
        jLSelectAgregarPaq = new javax.swing.JLabel();
        jLSelectEliminarPaq = new javax.swing.JLabel();
        jLSelectAct = new javax.swing.JLabel();
        jLImgInventario = new javax.swing.JLabel();
        jLImgEstado = new javax.swing.JLabel();
        jLImgEliminar = new javax.swing.JLabel();
        jLImgAgregar = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPBackground = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("Login"); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 32, 50));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 32, 50));

        jPControl.setBackground(new java.awt.Color(51, 51, 51));
        jPControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSelectH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectHMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 230, 52));

        jMinimizarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Menu_32px.png"))); // NOI18N
        jMinimizarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMinimizarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinimizarMenuMouseClicked(evt);
            }
        });
        jPControl.add(jMinimizarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 30));

        jLHome.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLHome.setForeground(new java.awt.Color(111, 174, 2));
        jLHome.setText("Home");
        jPControl.add(jLHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLLineaH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 85, 220, 20));

        jLSelectA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectAMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 230, 52));

        jLAdministracion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLAdministracion.setForeground(new java.awt.Color(111, 174, 2));
        jLAdministracion.setText("Administración");
        jPControl.add(jLAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 127, -1, -1));

        jLLineaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 142, 220, 20));

        jLSelectP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectPMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 171, 230, 52));

        jLPaqueteria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLPaqueteria.setForeground(new java.awt.Color(111, 174, 2));
        jLPaqueteria.setText("Paqueteria");
        jPControl.add(jLPaqueteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, -1, -1));

        jLLineaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 197, 220, 20));

        jLSelectF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectFMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 52));

        jLFactura.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLFactura.setForeground(new java.awt.Color(111, 174, 2));
        jLFactura.setText("Factura");
        jPControl.add(jLFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLLineaF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 255, 220, 20));

        jLSelectI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectIMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 230, 52));

        jLIncidentes.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLIncidentes.setForeground(new java.awt.Color(111, 174, 2));
        jLIncidentes.setText("Incidentes");
        jPControl.add(jLIncidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 297, -1, -1));

        jLLineaI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 312, 220, 20));

        jLSelectT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectTMouseClicked(evt);
            }
        });
        jPControl.add(jLSelectT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 342, 230, 52));

        jLTransporte.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLTransporte.setForeground(new java.awt.Color(111, 174, 2));
        jLTransporte.setText("Transporte");
        jPControl.add(jLTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 352, -1, -1));

        jLLineaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLineaT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/line2.png"))); // NOI18N
        jPControl.add(jLLineaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 367, 220, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPControl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 440, 40, 40));

        btnAdm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/administracion.png"))); // NOI18N
        jPControl.add(btnAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 120, 40, 33));

        btnPac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/caja.png"))); // NOI18N
        jPControl.add(btnPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 180, 40, 33));

        btnFac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/factura.png"))); // NOI18N
        jPControl.add(btnFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 240, 40, 33));

        btnInc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/exclamacion.png"))); // NOI18N
        jPControl.add(btnInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 295, 40, 33));

        btnTran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/camion.png"))); // NOI18N
        jPControl.add(btnTran, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 350, 40, 33));

        btnHom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Home_32px.png"))); // NOI18N
        jPControl.add(btnHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 67, 40, 33));

        jMenu.setForeground(new java.awt.Color(111, 174, 2));
        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/PANEL.png"))); // NOI18N
        jPControl.add(jMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 497));

        getContentPane().add(jPControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 2, 230, 497));

        jPAdministracion.setOpaque(false);
        jPAdministracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Administración");
        jPAdministracion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, -1));

        getContentPane().add(jPAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jPIncidentes.setOpaque(false);
        jPIncidentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Incidentes");
        jPIncidentes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, -1));

        getContentPane().add(jPIncidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jPFactura.setOpaque(false);
        jPFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Factura");
        jPFactura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, -1));

        getContentPane().add(jPFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jPTransporte.setOpaque(false);
        jPTransporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Transporte");
        jPTransporte.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, -1));

        getContentPane().add(jPTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jPPaqueteria.setMaximumSize(new java.awt.Dimension(950, 500));
        jPPaqueteria.setMinimumSize(new java.awt.Dimension(950, 500));
        jPPaqueteria.setName(""); // NOI18N
        jPPaqueteria.setOpaque(false);
        jPPaqueteria.setPreferredSize(new java.awt.Dimension(950, 500));
        jPPaqueteria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSelectInventario.setToolTipText("");
        jLSelectInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2), 2));
        jLSelectInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSelectInventario.setName("Inventario"); // NOI18N
        jPPaqueteria.add(jLSelectInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, 130));

        jLSelectAgregarPaq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2), 2));
        jLSelectAgregarPaq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPaqueteria.add(jLSelectAgregarPaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 140, 130));

        jLSelectEliminarPaq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2), 2));
        jLSelectEliminarPaq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPaqueteria.add(jLSelectEliminarPaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 140, 130));

        jLSelectAct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2), 2));
        jLSelectAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPPaqueteria.add(jLSelectAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 140, 130));

        jLImgInventario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLImgInventario.setForeground(new java.awt.Color(204, 204, 204));
        jLImgInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImgInventario.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\Downloads\\gestion-de-materiales (1).png")); // NOI18N
        jLImgInventario.setText("Inventario");
        jLImgInventario.setToolTipText("");
        jLImgInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLImgInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLImgInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPPaqueteria.add(jLImgInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));

        jLImgEstado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLImgEstado.setForeground(new java.awt.Color(204, 204, 204));
        jLImgEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImgEstado.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\Downloads\\estado.png")); // NOI18N
        jLImgEstado.setText("Estado");
        jLImgEstado.setToolTipText("");
        jLImgEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLImgEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLImgEstado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPPaqueteria.add(jLImgEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 100, -1));

        jLImgEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLImgEliminar.setForeground(new java.awt.Color(204, 204, 204));
        jLImgEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImgEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\Downloads\\eliminar.png")); // NOI18N
        jLImgEliminar.setText("Eliminar");
        jLImgEliminar.setToolTipText("");
        jLImgEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLImgEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLImgEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPPaqueteria.add(jLImgEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 100, -1));

        jLImgAgregar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLImgAgregar.setForeground(new java.awt.Color(204, 204, 204));
        jLImgAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLImgAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\migue\\Downloads\\anadir.png")); // NOI18N
        jLImgAgregar.setText("Agregar");
        jLImgAgregar.setToolTipText("");
        jLImgAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLImgAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLImgAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPPaqueteria.add(jLImgAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, -1));

        jLTitulo.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLTitulo.setText("Gestión Integral de Paquetes");
        jPPaqueteria.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, -1));

        jSeparator1.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator1.setForeground(new java.awt.Color(111, 174, 2));
        jPPaqueteria.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 890, 20));

        jSeparator2.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator2.setForeground(new java.awt.Color(111, 174, 2));
        jPPaqueteria.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 890, 20));

        jPInventario.setOpaque(false);
        jPInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPInventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 610, 380));

        jPPaqueteria.add(jPInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        getContentPane().add(jPPaqueteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 500));

        jPBackground.setPreferredSize(new java.awt.Dimension(700, 500));
        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/Login.png"))); // NOI18N
        jPBackground.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "Salir", dialogButton);
            if(resultado == 0){
                System.exit(0);
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(proyecto_encomienda.GESTION_PAQUETES.FRONTEND.PaqueteMenu.ICONIFIED);
        this.mover.setBandera(true);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void jMinimizarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizarMenuMouseClicked
        this.mover.startAnimation(jPControl, 180);

    }//GEN-LAST:event_jMinimizarMenuMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "Cerrar Sesión", dialogButton);
            if(resultado == 0){
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.mover.startAnimation(jPControl, 180);
        jLLineaH.setVisible(true);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(false);
        
        jPPaqueteria.setVisible(false);
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(false);
        jPInventario.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void jLSelectHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectHMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(true);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(false);
        

        jPPaqueteria.setVisible(false);
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(false);
    }//GEN-LAST:event_jLSelectHMouseClicked

    private void jLSelectAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectAMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(false);
        jLLineaA.setVisible(true);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(false);
        
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(true);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(false);
    }//GEN-LAST:event_jLSelectAMouseClicked

    private void jLSelectPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectPMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(false);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(true);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(false);
        
        jPPaqueteria.setVisible(true);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(false);
        
    }//GEN-LAST:event_jLSelectPMouseClicked

    private void jLSelectFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectFMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(false);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(true);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(false);
        
        jPPaqueteria.setVisible(false);
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(true);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(false);
    }//GEN-LAST:event_jLSelectFMouseClicked

    private void jLSelectIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectIMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(false);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(true);
        jLLineaT.setVisible(false);
        
        jPPaqueteria.setVisible(false);
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(false);
        jPIncidentes.setVisible(true);
        
    }//GEN-LAST:event_jLSelectIMouseClicked

    private void jLSelectTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectTMouseClicked
        this.mover.setBandera(true);
        jLLineaH.setVisible(false);
        jLLineaA.setVisible(false);
        jLLineaP.setVisible(false);
        jLLineaF.setVisible(false);
        jLLineaI.setVisible(false);
        jLLineaT.setVisible(true);
        
        jPPaqueteria.setVisible(false);
        jPPaqueteria.setVisible(false);
        jPAdministracion.setVisible(false);
        jPFactura.setVisible(false);
        jPTransporte.setVisible(true);
        jPIncidentes.setVisible(false);
    }//GEN-LAST:event_jLSelectTMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaqueteMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdm;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnFac;
    private javax.swing.JLabel btnHom;
    private javax.swing.JLabel btnInc;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnPac;
    private javax.swing.JLabel btnTran;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAdministracion;
    private javax.swing.JLabel jLFactura;
    private javax.swing.JLabel jLHome;
    private javax.swing.JLabel jLImgAgregar;
    private javax.swing.JLabel jLImgEliminar;
    private javax.swing.JLabel jLImgEstado;
    private javax.swing.JLabel jLImgInventario;
    private javax.swing.JLabel jLIncidentes;
    private javax.swing.JLabel jLLineaA;
    private javax.swing.JLabel jLLineaF;
    private javax.swing.JLabel jLLineaH;
    private javax.swing.JLabel jLLineaI;
    private javax.swing.JLabel jLLineaP;
    private javax.swing.JLabel jLLineaT;
    private javax.swing.JLabel jLPaqueteria;
    private javax.swing.JLabel jLSelectA;
    private javax.swing.JLabel jLSelectAct;
    private javax.swing.JLabel jLSelectAgregarPaq;
    private javax.swing.JLabel jLSelectEliminarPaq;
    private javax.swing.JLabel jLSelectF;
    private javax.swing.JLabel jLSelectH;
    private javax.swing.JLabel jLSelectI;
    private javax.swing.JLabel jLSelectInventario;
    private javax.swing.JLabel jLSelectP;
    private javax.swing.JLabel jLSelectT;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTransporte;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel jMenu;
    private javax.swing.JLabel jMinimizarMenu;
    private javax.swing.JPanel jPAdministracion;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPControl;
    private javax.swing.JPanel jPFactura;
    private javax.swing.JPanel jPIncidentes;
    private javax.swing.JPanel jPInventario;
    private javax.swing.JPanel jPPaqueteria;
    private javax.swing.JPanel jPTransporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
