/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_encomienda.GESTION_PAQUETES.FRONTEND;
import AppPackage.AnimationClass;
import proyecto_encomienda.GESTION_PAQUETES.FRONTEND.ClasesExtras.MovePanelWithAnimation;
import javax.swing.JOptionPane;
import proyecto_encomienda.INCIDENTES.GestorIncidentes;

/**
 *
 * @author migue
 */

public class PaqueteMenu extends javax.swing.JFrame {
    
    MovePanelWithAnimation mover;
    /**
     * Creates new form Paquete
     */
    public PaqueteMenu() {
        initComponents();
        this.setLocationRelativeTo(null); //Se centre la pantalla
        this.mover = new MovePanelWithAnimation();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPControl = new javax.swing.JPanel();
        jMinimizarMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLHome = new javax.swing.JLabel();
        jLHome1 = new javax.swing.JLabel();
        jLHome2 = new javax.swing.JLabel();
        jLHome3 = new javax.swing.JLabel();
        jLHome4 = new javax.swing.JLabel();
        jLHome5 = new javax.swing.JLabel();
        jMenu = new javax.swing.JLabel();
        jPBackground = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("Login"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPControl.setBackground(new java.awt.Color(51, 51, 51));
        jPControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMinimizarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Menu_32px.png"))); // NOI18N
        jMinimizarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMinimizarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinimizarMenuMouseClicked(evt);
            }
        });
        jPControl.add(jMinimizarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(111, 174, 2));
        jLabel2.setText("Administración");
        jPControl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 127, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 174, 2));
        jLabel3.setText("Home");
        jPControl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(111, 174, 2));
        jLabel4.setText("Incidentes");
        jPControl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 297, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 174, 2));
        jLabel7.setText("Paqueteria");
        jPControl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 174, 2));
        jLabel8.setText("Factura");
        jPControl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 174, 2));
        jLabel9.setText("Transporte");
        jPControl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 352, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPControl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 40, 40));
        jPControl.add(jLHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 30, 30));
        jPControl.add(jLHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 30, 30));
        jPControl.add(jLHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 30, 30));
        jPControl.add(jLHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 30, 30));
        jPControl.add(jLHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 30, 30));

        jLHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Home_32px.png"))); // NOI18N
        jPControl.add(jLHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 67, 30, 30));

        jMenu.setForeground(new java.awt.Color(111, 174, 2));
        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/PANEL.png"))); // NOI18N
        jPControl.add(jMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 497));

        getContentPane().add(jPControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 230, 497));

        jPBackground.setPreferredSize(new java.awt.Dimension(700, 500));
        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPBackground.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 32, 50));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPBackground.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 32, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/Login.png"))); // NOI18N
        jPBackground.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "Salir", dialogButton);
            if(resultado == 0){
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(proyecto_encomienda.GESTION_PAQUETES.FRONTEND.PaqueteMenu.ICONIFIED);
        this.mover.setBandera(false);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void jMinimizarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizarMenuMouseClicked
        this.mover.startAnimation(jPControl, 180);

    }//GEN-LAST:event_jMinimizarMenuMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "Cerrar Sesión", dialogButton);
            if(resultado == 0){
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaqueteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaqueteMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLHome;
    private javax.swing.JLabel jLHome1;
    private javax.swing.JLabel jLHome2;
    private javax.swing.JLabel jLHome3;
    private javax.swing.JLabel jLHome4;
    private javax.swing.JLabel jLHome5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jMenu;
    private javax.swing.JLabel jMinimizarMenu;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPControl;
    // End of variables declaration//GEN-END:variables
}
