/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_encomienda.GESTION_PAQUETES.FRONTEND;
import AppPackage.AnimationClass;

import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class Paquete extends javax.swing.JFrame {

    /**
     * Creates new form Paquete
     */
    public Paquete() {
        initComponents();
        this.setLocationRelativeTo(null); //Se centre la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JLabel();
        jPublic1 = new javax.swing.JLabel();
        jPublic2 = new javax.swing.JLabel();
        jPublic3 = new javax.swing.JLabel();
        jLineaS = new javax.swing.JLabel();
        jLineaI = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("Login"); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/NEXT.png"))); // NOI18N
        btnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 30));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/BACK.png"))); // NOI18N
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, -1, 30));

        jPublic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/paquete1.jpg"))); // NOI18N
        jPanel1.add(jPublic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 320));

        jPublic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/paquete2.jpg"))); // NOI18N
        jPanel1.add(jPublic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 1000, 320));

        jPublic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/DigClase.png"))); // NOI18N
        jPanel1.add(jPublic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2000, 100, 1000, 320));

        jLineaS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/paloPublic.png"))); // NOI18N
        jPanel1.add(jLineaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1000, 10));

        jLineaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/paloPublic.png"))); // NOI18N
        jPanel1.add(jLineaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 32, 50));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 32, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_encomienda/GESTION_PAQUETES/FRONTEND/imagenes/Login.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "EXIT", dialogButton);
            if(resultado == 0){
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(proyecto_encomienda.GESTION_PAQUETES.FRONTEND.Paquete.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorMouseClicked
        AnimationClass ac = new AnimationClass();
        ac.jLabelXRight(-2000, 0, 25, 5, jPublic1);
        
        AnimationClass acc = new AnimationClass();
        acc.jLabelXRight(-1000, 1000, 25, 5, jPublic2);
        
        AnimationClass accc = new AnimationClass();
        accc.jLabelXRight(0, 2000, 25, 5, jPublic3);
    }//GEN-LAST:event_btnAnteriorMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        AnimationClass ac = new AnimationClass();
        ac.jLabelXLeft(0, -2000, 25, 5, jPublic1);
        
        AnimationClass acc = new AnimationClass();
        acc.jLabelXLeft(1000, -1000, 25, 5, jPublic2);
                
        AnimationClass accc = new AnimationClass();
        accc.jLabelXLeft(2000, 0, 25, 5, jPublic3);
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimationClass ac = new AnimationClass();
        ac.jLabelXLeft(0, -2000, 25, 5, jPublic1);
        
        AnimationClass acc = new AnimationClass();
        acc.jLabelXLeft(1000, -1000, 25, 5, jPublic2);
                
        AnimationClass accc = new AnimationClass();
        accc.jLabelXLeft(2000, 0, 25, 5, jPublic3);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnterior;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSiguiente;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLineaI;
    private javax.swing.JLabel jLineaS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPublic1;
    private javax.swing.JLabel jPublic2;
    private javax.swing.JLabel jPublic3;
    // End of variables declaration//GEN-END:variables
}
