/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUICONDUCTOR;

import GUI.*;
import basededatos.DataBase;
import proyecto_paquetes.JFIngresar;
import validaciones.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mod_administracion.Cliente;
import mod_incidentes.ErrorDireccion;
import mod_incidentes.GestorIncidente;
import mod_incidentes.Incidente;
import mod_incidentes.PaqueteEstropeado;
import mod_incidentes.PaquetePerdido;
import mod_paquetes.Entregado;
import mod_paquetes.Inventario;
import mod_paquetes.Paquete;
import mod_transporte.Asignacion;

/**
 *
 * @author USUARIO
 */
public class JFPaquetesCliente extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form JFLogin
     */
    public JFPaquetesCliente() {
        Inventario.obtenerInstancia().cargarInventario();
        setIconImage(new ImageIcon(getClass().
                getResource("/iconos/AjustesBest.png")).getImage());
        initComponents();    
        this.setLocationRelativeTo(null);
        seleccionIncidentes.setVisible(false);
        jLabel133.setVisible(false);
        jTablaPaquete.setVisible(false);
        jBRegistrarIncidente.setVisible(false);
        setTitle("Recuperar contraseña");
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exitP = new javax.swing.JPanel();
        exitTXT = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBInsertar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        seleccionIncidentes = new javax.swing.JComboBox<>();
        jLabel133 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablaPaquete = new javax.swing.JTable();
        jBRegistrarIncidente = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperación de contraseña");
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(146, 10, 48));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 24));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitP.setBackground(new java.awt.Color(146, 10, 48));
        exitP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitTXT.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        exitTXT.setForeground(new java.awt.Color(255, 255, 255));
        exitTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTXT.setText("X");
        exitTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTXTMouseExited(evt);
            }
        });
        exitP.add(exitTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 24));

        jPanel2.add(exitP, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        jTCodigo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTCodigo.setForeground(new java.awt.Color(204, 204, 204));
        jTCodigo.setBorder(null);
        jTCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCodigoFocusLost(evt);
            }
        });
        jTCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTCodigoMousePressed(evt);
            }
        });
        jPanel1.add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 237, -1));

        jLabel1.setText("CodigoPaquete:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jBInsertar.setBackground(new java.awt.Color(255, 250, 243));
        jBInsertar.setText("Ingresar");
        jBInsertar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBInsertarMouseExited(evt);
            }
        });
        jBInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jBInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 80, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 237, 10));

        jTCedula.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jTCedula.setForeground(new java.awt.Color(204, 204, 204));
        jTCedula.setBorder(null);
        jTCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCedulaFocusLost(evt);
            }
        });
        jTCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTCedulaMousePressed(evt);
            }
        });
        jTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(jTCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 237, -1));

        jLabel5.setText("Cédula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 237, 10));

        seleccionIncidentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Daño en el Paquete", "Error de Dirección", "Paquete Perdido", "Rechazo Entrega" }));
        seleccionIncidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionIncidentesActionPerformed(evt);
            }
        });
        jPanel1.add(seleccionIncidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel133.setText("Tipo de incidente:");
        jPanel1.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTablaPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTablaPaquete);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 460, 70));

        jBRegistrarIncidente.setText("Registrar");
        jBRegistrarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarIncidenteActionPerformed(evt);
            }
        });
        jPanel1.add(jBRegistrarIncidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jBRegresar.setBackground(new java.awt.Color(255, 250, 243));
        jBRegresar.setText("Regresar");
        jBRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBRegresarMouseExited(evt);
            }
        });
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 101, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertarActionPerformed
        Cliente cliente = DataBase.obtenerInstancia().obtenerclientePorCedula(jTCedula.getText());
        Paquete paquete = Inventario.obtenerInstancia().obtenerPaquete(jTCodigo.getText());
        if(cliente == null || paquete == null){
            JOptionPane.showMessageDialog(null, "No Existen datos","Alguno de los datos no se encontraron", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        if(paquete.getRemitente().getCedula().equals(cliente.getCedula())){
            seleccionIncidentes.setVisible(true);
            jLabel133.setVisible(true);
            jTablaPaquete.setVisible(true);
            jBRegistrarIncidente.setVisible(true);
            DefaultTableModel model = new DefaultTableModel();
        jTablaPaquete.setModel(model);
        String[] columnNames = {
            "Código de Tracking", "Volumen", "Peso", "Contenido", 
            "Remitente", "Estado", "Provincia Destino"
        };
        model.setColumnIdentifiers(columnNames);
        model.addRow(new Object[]{
        paquete.obtenerCodigo(),
        paquete.getVolumen(),
        paquete.getPeso(),
        paquete.getContenido(),
        paquete.getRemitente().toString(),
        paquete.obtenerEstado().toString(),
        paquete.getProvinciaDestino().name()
        });
        
            return;
        }
        JOptionPane.showMessageDialog(null, "No Coinciden los datos","NO SEA SAPO", JOptionPane.ERROR_MESSAGE);
       
    }//GEN-LAST:event_jBInsertarActionPerformed

    private void jTCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCodigoMousePressed
        if (jTCodigo.getText().equals("Ingrese su documento de identidad")) {
            jTCodigo.setForeground(Color.black);
            jTCodigo.setText("");
        }

    }//GEN-LAST:event_jTCodigoMousePressed

    private void jTCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCodigoFocusLost
        if (jTCodigo.getText().isEmpty()) {
            jTCodigo.setText("Ingrese su documento de identidad");
            jTCodigo.setForeground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_jTCodigoFocusLost

    private void exitTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTXTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTXTMouseClicked

    private void exitTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTXTMouseEntered
        exitP.setBackground(Color.red);
    }//GEN-LAST:event_exitTXTMouseEntered

    private void exitTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTXTMouseExited
        exitP.setBackground(new Color(146, 10, 48));
    }//GEN-LAST:event_exitTXTMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jBInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInsertarMouseEntered
        jBInsertar.setBackground(new Color(255, 51, 133));
    }//GEN-LAST:event_jBInsertarMouseEntered

    private void jBInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInsertarMouseExited
        jBInsertar.setBackground(new Color(255, 250, 243));
    }//GEN-LAST:event_jBInsertarMouseExited

    private void jTCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCedulaFocusLost

    private void jTCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCedulaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCedulaMousePressed

    private void jTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCedulaActionPerformed

    private void seleccionIncidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionIncidentesActionPerformed
        
    }//GEN-LAST:event_seleccionIncidentesActionPerformed

    private void jBRegistrarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarIncidenteActionPerformed
        String incidente = (String) seleccionIncidentes.getSelectedItem();
        Paquete paquete = Inventario.obtenerInstancia().obtenerPaquete(jTCodigo.getText());
        Incidente incidenteRegistrar = new ErrorDireccion();
        if (incidente.equals("Error Dirección")) {
            incidenteRegistrar = new ErrorDireccion();
        } else if (incidente.equals("Paquete Estropeado")) {
            incidenteRegistrar = new PaqueteEstropeado();
        } else if (incidente.equals("Paquete Perdido")) {
            incidenteRegistrar = new PaquetePerdido();
        }
        if (!(paquete.obtenerEstado() instanceof Entregado)) {
            JOptionPane.showMessageDialog(
                null,
                "El paquete se encuentra fuera de su jurisdicción",
                "Registro falló",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro de que deseas registrar este incidente?",
            "Confirmación de registro",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (respuesta == JOptionPane.YES_OPTION) {
            GestorIncidente gi = new GestorIncidente(incidenteRegistrar);
            gi.crearIncidente(paquete);
            JOptionPane.showMessageDialog(
                null,
                "El incidente se ha registrado",
                "Registro Exitoso",
                JOptionPane.INFORMATION_MESSAGE
            );
            Inventario.obtenerInstancia().guardarInventario();
            DefaultTableModel modeloTabla = (DefaultTableModel) jTablaPaquete.getModel();
            modeloTabla.setRowCount(0);            
        } else {
            JOptionPane.showMessageDialog(
                null,
                "El registro del incidente se ha cancelado",
                "Registro Cancelado",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jBRegistrarIncidenteActionPerformed

    private void jBRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegresarMouseEntered
        jBRegresar.setBackground(new Color(255, 51, 133));
    }//GEN-LAST:event_jBRegresarMouseEntered

    private void jBRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegresarMouseExited
        jBRegresar.setBackground(new Color(255, 250, 243));
    }//GEN-LAST:event_jBRegresarMouseExited

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        this.dispose();
        JFIngresar ingresar = new JFIngresar();
        ingresar.setVisible(true);
    }//GEN-LAST:event_jBRegresarActionPerformed
    private void recuperarContrasena(String CI, int numpregunta, String respuesta) {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPaquetesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPaquetesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPaquetesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPaquetesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPaquetesCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exitP;
    private javax.swing.JLabel exitTXT;
    private javax.swing.JButton jBInsertar;
    private javax.swing.JButton jBRegistrarIncidente;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTCedula;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTable jTablaPaquete;
    private javax.swing.JComboBox<String> seleccionIncidentes;
    // End of variables declaration//GEN-END:variables
}
